pipeline {
    agent any

    environment {
        APP_NAME = "show-catalog-service"
        VERSION  = "1.0.1"
        IMAGE    = "suryadasari31/show-catalog-service:${VERSION}"

        SERVICE_DIR = "services/show-catalog-service"
        K8S_DIR     = "services/show-catalog-service/k8s"

        MAVEN_SETTINGS = "/var/lib/jenkins/.m2/settings.xml"
        OC_BIN = "/var/lib/jenkins/bin/oc"
        // OCP_API and OCP_PROJECT come from Jenkins Global Env Vars
    }

    stages {

        stage('Build') {
            steps {
                dir(SERVICE_DIR) {
                    sh "mvn -s ${MAVEN_SETTINGS} clean package"
                }
            }
        }

        stage('Publish Artifact to Nexus') {
            steps {
                dir(SERVICE_DIR) {
                    sh "mvn -s ${MAVEN_SETTINGS} deploy"
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir(SERVICE_DIR) {
                    sh "docker build -t ${IMAGE} ."
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh """
                        echo "\$DOCKER_PASS" | docker login -u "\$DOCKER_USER" --password-stdin
                        docker push ${IMAGE}
                    """
                }
            }
        }

        stage('Authenticate to OpenShift') {
            steps {
                withCredentials([
                    string(
                        credentialsId: 'openshift-sa-token',
                        variable: 'OS_TOKEN'
                    )
                ]) {
                    sh '''
                        /var/lib/jenkins/bin/oc logout || true
                        /var/lib/jenkins/bin/oc login "$OCP_API" --token="$OS_TOKEN" --insecure-skip-tls-verify=true
                        /var/lib/jenkins/bin/oc project "$OCP_PROJECT"
                    '''
                }
            }
        }

        stage('Deploy to OpenShift') {
            steps {
                sh '''
                    /var/lib/jenkins/bin/oc apply -f $K8S_DIR/deployment.yaml
                    /var/lib/jenkins/bin/oc apply -f $K8S_DIR/service.yaml
                    /var/lib/jenkins/bin/oc apply -f $K8S_DIR/route.yaml
                '''
            }
        }
    }

    post {
        success {
            echo "CI/CD pipeline completed successfully"
        }
        failure {
            echo "CI/CD pipeline failed"
        }
    }
}
