pipeline {
    agent any

    environment {
        APP_NAME     = "show-catalog-service"
        VERSION      = "1.0.1"
        IMAGE        = "suryadasari31/show-catalog-service:${VERSION}"

        SERVICE_DIR = "services/show-catalog-service"
        K8S_DIR     = "services/show-catalog-service/k8s"

        MAVEN_SETTINGS = "/var/lib/jenkins/.m2/settings.xml"

        OCP_API     = "https://api.rm2.thpm.p1.openshiftapps.com:6443"
        OCP_PROJECT = "suryadasari31-dev"
    }

    stages {

        /* -------------------------------------------------
           BUILD STAGE
           ------------------------------------------------- */
        stage('Build') {
            steps {
                dir("${SERVICE_DIR}") {
                    sh """
                    mvn -s ${MAVEN_SETTINGS} clean package
                    """
                }
            }
        }

        /* -------------------------------------------------
           PUBLISH ARTIFACT TO NEXUS
           ------------------------------------------------- */
        stage('Publish Artifact to Nexus') {
            steps {
                dir("${SERVICE_DIR}") {
                    sh """
                    mvn -s ${MAVEN_SETTINGS} deploy
                    """
                }
            }
        }

        /* -------------------------------------------------
           DOCKER BUILD
           ------------------------------------------------- */
        stage('Docker Build') {
            steps {
                dir("${SERVICE_DIR}") {
                    sh """
                    docker build -t ${IMAGE} .
                    """
                }
            }
        }

        /* -------------------------------------------------
           DOCKER PUSH
           ------------------------------------------------- */
        stage('Docker Push') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
